apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - name: shipping
        image: 164910480407.dkr.ecr.us-east-1.amazonaws.com/shipping:011
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: shipping-configmap

--- 

apiVersion: v1
kind: Service
metadata:
  name: shipping-svc
spec:
  selector:
   app: shipping
  ports:
    - protocol: TCP
      port: 8080              # Port number of the service that it has to listen on 
      targetPort: 8080        # Port number of the container that it has to forward to

--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-configmap
data:
  CART_ENDPOINT: "cart-svc:8080"  
  DB_HOST: "terraform-20231209180735201800000001.cecqgmgakd6o.us-east-1.rds.amazonaws.com" 

--- 

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75